# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/felix/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),felix)

$(call add-radio-file-sha1-checked,radio/abl.img,b24507aac5489592737d7498889f68a1caa2922a)
$(call add-radio-file-sha1-checked,radio/bl1.img,8e6bc7059528ec7652e5d9d82063b0c9f20a6ff6)
$(call add-radio-file-sha1-checked,radio/bl2.img,9b1c32202a05885cd5258a71770876a78511616f)
$(call add-radio-file-sha1-checked,radio/bl31.img,eb89b23b09d63173c19050b23235d883de691c2c)
$(call add-radio-file-sha1-checked,radio/gsa.img,450a128fff043286b158082818f98898bc90e893)
$(call add-radio-file-sha1-checked,radio/ldfw.img,b5359655db3864e990bbb5de1ee58923d30d91b0)
$(call add-radio-file-sha1-checked,radio/modem.img,0331530cdf89a9d98f4ceecc315233ec69ca3fd9)
$(call add-radio-file-sha1-checked,radio/pbl.img,629ea876c21744e8bde203f214dd6cf547e64cda)
$(call add-radio-file-sha1-checked,radio/tzsw.img,f3ccb6f2726e0bb4c6a9e889c2307332ec85d84d)

endif
